Feature/list markup
skojphy/switea pull request #31
Opened 2021-11-09 11:52 UTC by skojphy

- 스터디 목록 보기 페이지 마크업

2021-11-09 12:21 UTC, Hoya-kim requested changes
수정사항 확인하고 푸시해주세여!

2021-11-09 12:21 UTC, Hoya-kim commented on src/pages/list.html
> +    <title>Document</title>
Title 변경하쉴?

2021-11-09 12:21 UTC, Hoya-kim commented on src/pages/list.html
> +      <h1 class="logo">
a11yHidden 클래스 추가해 주쉴?

2021-11-09 12:21 UTC, Hoya-kim commented on src/pages/list.html
> +      <main class="list-view">
list-container 어떠심?
다른 것들도 container쓸꺼임여

2021-11-09 12:21 UTC, Hoya-kim commented on src/pages/list.html
> +        <form action="#">
action 어트리뷰트 제거해 주쉴?

2021-11-09 12:21 UTC, Hoya-kim commented on src/pages/list.html
> +            <legend>검색 폼</legend>
"스터디 검색 폼"으로 바꿔주쉴??

2021-11-09 12:21 UTC, Hoya-kim commented on src/pages/list.html
> +                <input
label 추가 해주쉴? 
aria-label 제거하고
```html
<label><input/></label>
```

2021-11-09 12:38 UTC, congaweb requested changes

2021-11-09 12:38 UTC, congaweb commented on src/pages/list.html
> +            <div class="study-lists__profile">
a태그로 콘텐츠 감싸주쉴?

2021-11-09 15:05 UTC, skojphy commented on src/pages/list.html
> +                <input
하단의 다른 input 요소와 통일하여 명시적 방법으로 label 넣어서 수정해도 될까요?

2021-11-10 01:09 UTC, Hoya-kim commented
Confirm.

2021-11-10 01:09 UTC, jiwonkim0131 commented
허어락~

2021-11-10 01:09 UTC, merged